# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingentry',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 9, 23, 25, 402635)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 9, 23, 25, 401465)),
        ),
    ]
